/**
 * ddlGenerator.ts — SQL DDL generator
 * Port of generate_ddl_scripts from profiler.py
 */

import type { ColumnProfile, DDLDialect } from "@/types";

type TypeMap = Record<DDLDialect, string>;

const TYPE_MAPPINGS: Record<string, TypeMap> = {
  "Primary Key": {
    postgresql: "SERIAL PRIMARY KEY",
    mysql: "INT AUTO_INCREMENT PRIMARY KEY",
    sqlite: "INTEGER PRIMARY KEY AUTOINCREMENT",
    snowflake: "VARCHAR(255) PRIMARY KEY",
    sql_server: "INT IDENTITY(1,1) PRIMARY KEY",
    oracle: "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
  },
  "Unique Identifier": {
    postgresql: "VARCHAR(255) UNIQUE",
    mysql: "VARCHAR(255) UNIQUE",
    sqlite: "TEXT UNIQUE",
    snowflake: "VARCHAR(255) UNIQUE",
    sql_server: "VARCHAR(255) UNIQUE",
    oracle: "VARCHAR2(255) UNIQUE",
  },
  "Email Address": {
    postgresql: "VARCHAR(255)",
    mysql: "VARCHAR(255)",
    sqlite: "TEXT",
    snowflake: "VARCHAR(255)",
    sql_server: "VARCHAR(255)",
    oracle: "VARCHAR2(255)",
  },
  "URL / Link": {
    postgresql: "VARCHAR(512)",
    mysql: "VARCHAR(512)",
    sqlite: "TEXT",
    snowflake: "VARCHAR(512)",
    sql_server: "VARCHAR(512)",
    oracle: "VARCHAR2(512)",
  },
  "Phone Number": {
    postgresql: "VARCHAR(50)",
    mysql: "VARCHAR(50)",
    sqlite: "TEXT",
    snowflake: "VARCHAR(50)",
    sql_server: "VARCHAR(50)",
    oracle: "VARCHAR2(50)",
  },
  "DateTime": {
    postgresql: "TIMESTAMP",
    mysql: "DATETIME",
    sqlite: "TEXT",
    snowflake: "TIMESTAMP_NTZ",
    sql_server: "DATETIME2",
    oracle: "TIMESTAMP",
  },
  "Currency": {
    postgresql: "NUMERIC(15, 2)",
    mysql: "DECIMAL(15, 2)",
    sqlite: "REAL",
    snowflake: "NUMBER(15, 2)",
    sql_server: "DECIMAL(15, 2)",
    oracle: "NUMBER(15, 2)",
  },
  "Zip / Postal Code": {
    postgresql: "VARCHAR(20)",
    mysql: "VARCHAR(20)",
    sqlite: "TEXT",
    snowflake: "VARCHAR(20)",
    sql_server: "VARCHAR(20)",
    oracle: "VARCHAR2(20)",
  },
  "Boolean / Flag": {
    postgresql: "BOOLEAN",
    mysql: "TINYINT(1)",
    sqlite: "INTEGER",
    snowflake: "BOOLEAN",
    sql_server: "BIT",
    oracle: "NUMBER(1)",
  },
  "Category": {
    postgresql: "VARCHAR(100)",
    mysql: "VARCHAR(100)",
    sqlite: "TEXT",
    snowflake: "VARCHAR(100)",
    sql_server: "VARCHAR(100)",
    oracle: "VARCHAR2(100)",
  },
  "Numeric (Integer)": {
    postgresql: "INTEGER",
    mysql: "INT",
    sqlite: "INTEGER",
    snowflake: "NUMBER",
    sql_server: "INT",
    oracle: "NUMBER",
  },
  "Numeric (Float)": {
    postgresql: "DOUBLE PRECISION",
    mysql: "DOUBLE",
    sqlite: "REAL",
    snowflake: "DOUBLE",
    sql_server: "FLOAT",
    oracle: "NUMBER",
  },
  "Text / String": {
    postgresql: "TEXT",
    mysql: "TEXT",
    sqlite: "TEXT",
    snowflake: "VARCHAR",
    sql_server: "NVARCHAR(MAX)",
    oracle: "CLOB",
  },
  "Empty / Missing": {
    postgresql: "VARCHAR(255)",
    mysql: "VARCHAR(255)",
    sqlite: "TEXT",
    snowflake: "VARCHAR(255)",
    sql_server: "VARCHAR(255)",
    oracle: "VARCHAR2(255)",
  },
};

// Fallback for any unmapped semantic types
const DEFAULT_TYPE: TypeMap = {
  postgresql: "TEXT",
  mysql: "TEXT",
  sqlite: "TEXT",
  snowflake: "VARCHAR",
  sql_server: "NVARCHAR(MAX)",
  oracle: "CLOB",
};

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^(\d)/, "_$1").slice(0, 63).toLowerCase();
}

function getDbType(semanticType: string, dialect: DDLDialect): string {
  return (TYPE_MAPPINGS[semanticType] ?? DEFAULT_TYPE)[dialect];
}

export function generateDDLScripts(filename: string, columns: ColumnProfile[]): Record<string, string> {
  const baseName = filename.replace(/\.[^/.]+$/, "");
  const tableName = sanitize(baseName) || "analyzed_dataset";
  const scripts: Record<string, string> = {};

  // PostgreSQL
  const pgCols = columns.map((c) => {
    const n = sanitize(c.name);
    const t = getDbType(c.semantic_type, "postgresql");
    const notNull = c.null_percentage === 0 && !t.includes("PRIMARY KEY") ? " NOT NULL" : "";
    return `  ${n} ${t}${notNull}`;
  });
  const pgComments = [
    `COMMENT ON TABLE ${tableName} IS 'Table generated by SchemaScribe AI for ${filename}';`,
    ...columns
      .filter((c) => c.description && !c.description.includes("pending"))
      .map((c) => `COMMENT ON COLUMN ${tableName}.${sanitize(c.name)} IS '${c.description.replace(/'/g, "''")}';`),
  ];
  scripts.postgresql = `CREATE TABLE ${tableName} (\n${pgCols.join(",\n")}\n);\n\n${pgComments.join("\n")}`;

  // MySQL
  const myCols = columns.map((c) => {
    const n = sanitize(c.name);
    const t = getDbType(c.semantic_type, "mysql");
    const notNull = c.null_percentage === 0 && !t.includes("PRIMARY KEY") ? " NOT NULL" : "";
    const desc = c.description && !c.description.includes("pending")
      ? ` COMMENT '${c.description.replace(/'/g, "''")}'`
      : "";
    return `  ${n} ${t}${notNull}${desc}`;
  });
  scripts.mysql = `CREATE TABLE ${tableName} (\n${myCols.join(",\n")}\n) ENGINE=InnoDB COMMENT='Table generated by SchemaScribe AI for ${filename}';`;

  // SQLite
  const slCols = columns.map((c) => {
    const n = sanitize(c.name);
    const t = getDbType(c.semantic_type, "sqlite");
    const notNull = c.null_percentage === 0 && !t.includes("PRIMARY KEY") ? " NOT NULL" : "";
    const desc = c.description && !c.description.includes("pending") ? ` -- ${c.description}` : "";
    return `  ${n} ${t}${notNull}${desc}`;
  });
  scripts.sqlite = `-- SQLite DDL generated by SchemaScribe AI for ${filename}\nCREATE TABLE ${tableName} (\n${slCols.join(",\n")}\n);`;

  // Snowflake
  const sfCols = columns.map((c) => {
    const n = sanitize(c.name);
    const t = getDbType(c.semantic_type, "snowflake");
    const notNull = c.null_percentage === 0 && !t.includes("PRIMARY KEY") ? " NOT NULL" : "";
    const desc = c.description && !c.description.includes("pending")
      ? ` COMMENT '${c.description.replace(/'/g, "''")}'`
      : "";
    return `  ${n} ${t}${notNull}${desc}`;
  });
  scripts.snowflake = `CREATE TABLE ${tableName} (\n${sfCols.join(",\n")}\n) COMMENT = 'Table generated by SchemaScribe AI for ${filename}';`;

  // SQL Server
  const ssCols = columns.map((c) => {
    const n = sanitize(c.name);
    const t = getDbType(c.semantic_type, "sql_server");
    const notNull = c.null_percentage === 0 && !t.includes("PRIMARY KEY") ? " NOT NULL" : "";
    const desc = c.description && !c.description.includes("pending") ? ` -- ${c.description}` : "";
    return `  ${n} ${t}${notNull}${desc}`;
  });
  scripts.sql_server = `-- Microsoft SQL Server DDL generated by SchemaScribe AI\nCREATE TABLE ${tableName} (\n${ssCols.join(",\n")}\n);`;

  // Oracle
  const oraCols = columns.map((c) => {
    const n = sanitize(c.name);
    const t = getDbType(c.semantic_type, "oracle");
    const notNull = c.null_percentage === 0 && !t.includes("PRIMARY KEY") ? " NOT NULL" : "";
    return `  ${n} ${t}${notNull}`;
  });
  const oraComments = [
    `COMMENT ON TABLE ${tableName} IS 'Table generated by SchemaScribe AI for ${filename}';`,
    ...columns
      .filter((c) => c.description && !c.description.includes("pending"))
      .map((c) => `COMMENT ON COLUMN ${tableName}.${sanitize(c.name)} IS '${c.description.replace(/'/g, "''").slice(0, 255)}';`),
  ];
  scripts.oracle = `CREATE TABLE ${tableName} (\n${oraCols.join(",\n")}\n);\n\n${oraComments.join("\n")}`;

  return scripts;
}
