import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { getSession, getFileBytes } from "@/lib/kvStore";
import { generateChatResponse } from "@/lib/describer";

export async function POST(req: NextRequest): Promise<NextResponse> {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { session_id, message } = await req.json();
  if (!session_id || !message) {
    return NextResponse.json({ error: "Missing session_id or message" }, { status: 400 });
  }

  const sessionData = await getSession(session_id);
  if (!sessionData) {
    return NextResponse.json({ error: "Session not found" }, { status: 404 });
  }

  const schemaText = sessionData.data.columns
    .map((c) => `${c.name} (${c.semantic_type}, ${c.pandas_dtype})`)
    .join("\n");

  const { code } = await generateChatResponse(schemaText, message);
  if (!code) {
    return NextResponse.json({ error: "Failed to generate answer" }, { status: 500 });
  }

  let finalAnswer = "I couldn't process that.";

  // If we have file data, we can execute the code to get a real answer
  if (sessionData.source_type === "file" && sessionData.filename !== "Multi-File Workspace") {
    try {
      const fileId = `${session_id}_${sessionData.filename}`;
      const bytes = await getFileBytes(fileId);
      if (bytes) {
        // Parse the file again (simplified for chat)
        let data: Record<string, unknown>[] = [];
        const ext = sessionData.filename.split(".").pop()?.toLowerCase();
        
        if (ext === "csv") {
          const Papa = (await import("papaparse")).default;
          const text = bytes.toString("utf-8");
          const result = Papa.parse<Record<string, unknown>>(text, {
            header: true,
            skipEmptyLines: true,
            dynamicTyping: true,
          });
          data = result.data;
        } else if (ext === "xlsx" || ext === "xls") {
          const XLSX = await import("xlsx");
          const wb = XLSX.read(bytes, { type: "buffer" });
          const ws = wb.Sheets[wb.SheetNames[0]];
          data = XLSX.utils.sheet_to_json<Record<string, unknown>>(ws);
        } else if (ext === "json") {
          const parsed = JSON.parse(bytes.toString("utf-8"));
          data = Array.isArray(parsed) ? parsed : [parsed];
        }
        console.log(`[CHAT] Data loaded. Rows: ${data.length}`);

        // Robust extraction: if Groq wrapped in markdown, extract it.
        let cleanCode = code;
        const jsMatch = code.match(/```(?:javascript|js)\n([\s\S]*?)```/);
        if (jsMatch) {
          cleanCode = jsMatch[1];
        } else {
          // Fallback if it just used ``` without language or no formatting
          const rawMatch = code.match(/```\n([\s\S]*?)```/);
          if (rawMatch) {
            cleanCode = rawMatch[1];
          } else {
             cleanCode = code.replace(/```(?:javascript|js)/g, "").replace(/```/g, "");
          }
        }
        
        console.log("[CHAT CODE GENERATED]:\n", cleanCode);
        
        let runner;
        try {
          runner = new Function("data", `
            try {
              ${cleanCode}
              if (typeof result !== 'undefined') return result;
              return "No result was generated by AI.";
            } catch(e) {
              return "Error calculating answer: " + e.message;
            }
          `);
        } catch (compileError: any) {
          console.error("Syntax Error in AI Code:", compileError);
          finalAnswer = "AI generated invalid code syntax: " + compileError.message;
        }

        if (runner) {
          const result = runner(data);
          if (result !== undefined) {
            finalAnswer = typeof result === 'object' ? JSON.stringify(result) : String(result);
          }
        }
      } else {
         finalAnswer = "Data expired from memory. Please re-upload.";
      }
    } catch (e: any) {
      console.error(e);
      finalAnswer = "Error executing calculation: " + (e.message || "Unknown error");
    }
  } else {
    // For DB connections or Multi-file where we don't hold the raw data rows in memory, 
    // we just return the SQL query or code snippet instead.
    finalAnswer = `For databases, I generate SQL instead of executing JS. Based on your schema, you would run:\n\n\`\`\`sql\n${code}\n\`\`\``;
  }

  return NextResponse.json({ reply: finalAnswer });
}
